// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"github.com/google/wire"
	"go-clean-architecture/pkg/rabbitmq"
	"go-clean-architecture/server/api/contract"
	"go-clean-architecture/server/api/handler"
	"go-clean-architecture/server/api/repository"
	"go-clean-architecture/server/api/service"
	"go-clean-architecture/server/lib/database"
	"go-clean-architecture/server/lib/environment"
	"go-clean-architecture/server/lib/logger"
)

// Injectors from wire.go:

func InitializeAPI(cfg *environment.Config, log *logger.Logger) (*App, error) {
	db, err := database.ProvideSQLDatabase(cfg)
	if err != nil {
		return nil, err
	}
	projectRepository := repository.NewProjectRepository(db)
	projectService := service.NewProjectService(projectRepository, log)
	experienceRepository := repository.NewExperienceRepository(db)
	experienceService := service.NewExperienceService(experienceRepository, log)
	handlerHandler := handler.NewHandler(projectService, experienceService, log)
	rabbitMQClient, err := pkg.NewRabbitMQConnectionFromConfig(cfg)
	if err != nil {
		return nil, err
	}
	messagePublisher := repository.NewRabbitMQPublisherFromConfig(rabbitMQClient)
	app := NewApp(handlerHandler, rabbitMQClient, messagePublisher)
	return app, nil
}

// wire.go:

// Grouping services
var ProjectSet = wire.NewSet(repository.NewProjectRepository, wire.Bind(new(contract.IProjectRepository), new(*repository.ProjectRepository)), service.NewProjectService, wire.Bind(new(contract.IProjectService), new(*service.ProjectService)))

var ExperienceSet = wire.NewSet(repository.NewExperienceRepository, wire.Bind(new(contract.IExperienceRepository), new(*repository.ExperienceRepository)), service.NewExperienceService, wire.Bind(new(contract.IExperienceService), new(*service.ExperienceService)))

// PERUBAHAN DI SINI: Gunakan fungsi FromConfig agar wire tidak bingung mencari string parameter
var RabbitMQSet = wire.NewSet(pkg.NewRabbitMQConnectionFromConfig, repository.NewRabbitMQPublisherFromConfig)
